-- ============================================================================
-- TEMPLATE: criação de schema completo por cliente (multi-tenant)
-- Baseado no setup real de produção do cliente "Paulo Robson" (prefixo paulo_).
-- Rodar INTEIRO, de uma vez, no SQL Editor do Supabase (SQL puro, sem
-- depender de psql — usa um bloco DO $$ com EXECUTE dinâmico). Não altera
-- nada no schema "public" nem em nenhum outro schema já existente.
--
-- COMO USAR PARA UM NOVO CLIENTE:
--   1. Troque o valor de v_schema logo abaixo (única linha a editar).
--   2. Rode o arquivo inteiro, de uma vez, no SQL Editor do Supabase.
--   3. No Supabase, vá em Settings > API > Exposed schemas e adicione o nome
--      do schema novo, SE for expor essas tabelas via API REST (PostgREST).
--      Conexões diretas (n8n, psycopg2, etc.) não precisam disso.
--   4. Nos workflows n8n / scripts Python que apontarem para este cliente,
--      configure o campo "schema" (n8n) ou o search_path/schema() (Python)
--      para o nome do schema deste cliente, em vez de "public".
--
-- Este arquivo cria, dentro do schema do cliente:
--   - orcamentos              (uma linha por área/estrutura do orçamento)
--   - inss                    (resultado consolidado do diagnóstico)
--   - conversas_leads         (buffer de debounce + controle de reaquecimento)
--   - reengajamento_textos    (textos-base do fluxo de reaquecimento)
--   - orcamento_seq           (contador diário para gerar numero_orcamento)
--   - função salvar_orcamento(jsonb) — equivalente a salvar_orcamento_v2(),
--     já apontando para as tabelas deste schema.
--
-- E, como ÚNICA EXCEÇÃO, em PUBLIC (não no schema do cliente):
--   - <cliente>_chat_histories  (ex: paulo_robson_chat_histories) — histórico
--     de mensagens usado como memória do AI Agent (LangChain). Fica em public
--     porque o node @n8n/n8n-nodes-langchain.memoryPostgresChat não suporta
--     schema customizado, só nome de tabela livre. Ver comentário na seção 5.
-- ============================================================================

DO $MAIN$
DECLARE
  -- --------------------------------------------------------------------------
  -- 0. NOME DO SCHEMA — troque aqui para cada cliente novo
  -- --------------------------------------------------------------------------
  v_schema TEXT := 'paulo_robson';
BEGIN

  -- ----------------------------------------------------------------------------
  -- 1. Criação do schema
  -- ----------------------------------------------------------------------------
  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_schema);

  -- ----------------------------------------------------------------------------
  -- 2. Tabela: orcamentos
  --    Espelho de paulo_orcamentos (produção). Uma linha por área/estrutura;
  --    várias linhas compartilham o mesmo numero_orcamento.
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS %I.orcamentos (
      id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
      nome               VARCHAR,
      telefone           VARCHAR NOT NULL,
      numero_orcamento   VARCHAR NOT NULL,
      session_id         TEXT,
      estado             VARCHAR,
      tipo               VARCHAR,
      categoria          VARCHAR,
      material           VARCHAR,
      area_m2            VARCHAR,
      is_principal       VARCHAR,
      coberta            VARCHAR,
      data_inicio        VARCHAR,
      data_fim           VARCHAR,
      concreto_usinado   VARCHAR DEFAULT 'nao',
      paralisacao        VARCHAR,
      prefabricado       VARCHAR DEFAULT 'nao',
      status_orcamento   TEXT DEFAULT 'aberto',
      meses_paralisados  TEXT
    )
  $f$, v_schema);

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS idx_orcamentos_tel_status ON %I.orcamentos (telefone, status_orcamento, created_at DESC)',
    v_schema);

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS idx_orcamentos_session_id ON %I.orcamentos (session_id)',
    v_schema);

  -- ----------------------------------------------------------------------------
  -- 3. Tabela: inss
  --    Espelho de paulo_inss (produção). Resultado consolidado do diagnóstico
  --    (INSS sem redução, otimizado, honorários, percentuais).
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS %I.inss (
      id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
      numero_orcamento            TEXT,
      nome                        TEXT,
      telefone                    TEXT,
      session_id                  TEXT,
      inss_sem_reducao            TEXT,
      inss_otimizado              TEXT,
      inss_com_honorarios         TEXT,
      honorarios                  TEXT,
      percentual_economia         TEXT,
      percentual_com_honorarios   TEXT
    )
  $f$, v_schema);

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS idx_inss_numero_orcamento ON %I.inss (numero_orcamento)',
    v_schema);

  -- ----------------------------------------------------------------------------
  -- 4. Tabela: conversas_leads
  --    Espelho de paulo_conversas_leads (produção). Chave = chatLid (Z-API),
  --    usada para debounce de mensagens e como gatilho do reaquecimento.
  --    telefone: número real do lead, só disponível após a 1ª mensagem recebida
  --    (a chave "id" é o chatLid, referência interna do WhatsApp — não o número).
  --    status: 'ativo' | 'bloqueado' (controle manual do operador via WhatsApp).
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS %I.conversas_leads (
      id                BIGINT PRIMARY KEY,
      created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
      timeout           TEXT NOT NULL,
      mensagem          TEXT,
      telefone          TEXT,
      status            TEXT NOT NULL DEFAULT 'ativo',
      last_message_at   TIMESTAMPTZ,
      enviado_1h        BOOLEAN NOT NULL DEFAULT false,
      enviado_4h        BOOLEAN NOT NULL DEFAULT false,
      enviado_1d        BOOLEAN NOT NULL DEFAULT false,
      enviado_3d        BOOLEAN NOT NULL DEFAULT false,
      enviado_7d        BOOLEAN NOT NULL DEFAULT false,
      enviado_15d       BOOLEAN NOT NULL DEFAULT false
    )
  $f$, v_schema);

  -- ----------------------------------------------------------------------------
  -- 5. Tabela: chat_histories — ÚNICA EXCEÇÃO ao padrão "tudo dentro do schema
  --    do cliente". Fica em PUBLIC, com nome prefixado pelo schema do cliente
  --    (ex: paulo_robson_chat_histories), porque o node
  --    @n8n/n8n-nodes-langchain.memoryPostgresChat (memória conversacional do
  --    AI Agent) NÃO tem parâmetro de schema — só "Table Name" (string livre).
  --    Confirmado via documentação/schema do node: não existe workaround via
  --    parâmetro ou credencial padrão do n8n. O isolamento entre clientes aqui
  --    vem do NOME da tabela, não do schema Postgres.
  --    Formato exigido pela memória Postgres do LangChain/n8n:
  --    message é um JSONB {"type": "human"|"ai", "content": "...", ...}.
  --    session_id = chatLid (mesma chave usada em conversas_leads.id, como texto).
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS public.%I (
      id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id   VARCHAR NOT NULL,
      message      JSONB NOT NULL,
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  $f$, v_schema || '_chat_histories');

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON public.%I (session_id)',
    'idx_' || v_schema || '_chat_histories_session_id',
    v_schema || '_chat_histories');

  EXECUTE format(
    'GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO anon, authenticated, service_role',
    v_schema || '_chat_histories');

  -- Nome real da sequence da coluna IDENTITY (não segue o padrão previsível
  -- de SERIAL — precisa ser resolvido via pg_get_serial_sequence)
  EXECUTE format(
    'GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated, service_role',
    pg_get_serial_sequence('public.' || quote_ident(v_schema || '_chat_histories'), 'id'));

  -- ----------------------------------------------------------------------------
  -- 6. Tabela: reengajamento_textos
  --    Espelho de paulo_reengajamento_textos (produção). Textos-base editáveis
  --    do fluxo de reaquecimento, por etapa da coleta x marco de tempo sem
  --    resposta (1h/4h/1d/3d/7d/15d).
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS %I.reengajamento_textos (
      etapa  TEXT NOT NULL,
      marco  TEXT NOT NULL,
      texto  TEXT NOT NULL,
      PRIMARY KEY (etapa, marco)
    )
  $f$, v_schema);

  -- ----------------------------------------------------------------------------
  -- 7. Tabela: orcamento_seq
  --    Contador diário atômico usado para montar numero_orcamento
  --    (formato AAMMDD + sequência de 2 dígitos, sem race condition).
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS %I.orcamento_seq (
      dia  DATE PRIMARY KEY,
      seq  INT NOT NULL DEFAULT 0
    )
  $f$, v_schema);

  -- ----------------------------------------------------------------------------
  -- 8. Função: salvar_orcamento
  --    Equivalente a salvar_orcamento_v2() de produção, já apontando para as
  --    tabelas deste schema (orcamentos, orcamento_seq). Mesmo contrato de
  --    payload_json (nome, telefone, session_id, estado, data_inicio, data_fim,
  --    concreto_usinado, paralisacao, paralisacoes[], areas[]).
  --
  --    Dedup: mesmo telefone + mesmo nome, últimos 10 min, reaproveita o número.
  --    Ciclo de status_orcamento: aberto -> processando -> processado (pipeline
  --    externo é quem promove os status; esta função só lida com 'aberto').
  -- ----------------------------------------------------------------------------
  EXECUTE format($f$
    CREATE OR REPLACE FUNCTION %I.salvar_orcamento(p JSONB)
    RETURNS TEXT AS $FUNC$
    DECLARE
      v_num   TEXT;
      v_seq   INT;
      v_dia   DATE := (now() AT TIME ZONE 'America/Sao_Paulo')::date;  -- data local, não UTC
      v_area  JSONB;
      v_par   JSONB;
      v_meses TEXT := NULL;
      v_chunk TEXT;
      v_ini   DATE;
      v_fim   DATE;
    BEGIN
      -- 0. VALIDAÇÃO: toda linha não-principal precisa de coberta sim/nao
      --    (o cálculo usa: coberta=50%%, descoberta=25%% — vale até para demolição).
      IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(p->'areas') a
        WHERE a->>'is_principal' = 'nao'
          AND coalesce(a->>'coberta', '') NOT IN ('sim', 'nao')
      ) THEN
        RAISE EXCEPTION 'DADOS INCOMPLETOS: toda area com is_principal=nao (piscina, garagem, demolicao etc) exige coberta=sim ou nao. Pergunte ao lead se a area/estrutura e coberta e chame a tool novamente com o payload completo corrigido.';
      END IF;

      -- 1. Expansão de meses paralisados (antes da dedup, que compara meses):
      --      {"inicio","fim"}      -> fim = ÚLTIMO mês parado (INCLUSIVO)
      --      {"inicio","retomada"} -> retomada = mês em que voltou (EXCLUSIVO)
      FOR v_par IN
        SELECT * FROM jsonb_array_elements(coalesce(p->'paralisacoes', '[]'::jsonb))
      LOOP
        v_ini := to_date(v_par->>'inicio', 'MM/YYYY');

        IF v_par ? 'retomada' AND coalesce(v_par->>'retomada', '') <> '' THEN
          v_fim := to_date(v_par->>'retomada', 'MM/YYYY') - interval '1 month';
        ELSIF coalesce(v_par->>'fim', '') <> '' THEN
          v_fim := to_date(v_par->>'fim', 'MM/YYYY');
        ELSE
          CONTINUE;  -- intervalo sem fim/retomada: ignora
        END IF;

        SELECT string_agg(to_char(d, 'MM/YYYY'), ',' ORDER BY d)
          INTO v_chunk
        FROM generate_series(v_ini, v_fim, interval '1 month') d;

        IF v_chunk IS NOT NULL THEN
          v_meses := CASE WHEN v_meses IS NULL THEN v_chunk
                          ELSE v_meses || ',' || v_chunk END;
        END IF;
      END LOOP;

      -- 2. DEDUP: mesma conversa? (mesmo telefone + MESMO NOME, últimos 10 min)
      --    Nome diferente = engenheiro simulando outro cliente -> número novo
      SELECT numero_orcamento INTO v_num
      FROM %I.orcamentos
      WHERE telefone = p->>'telefone'
        AND lower(trim(nome)) = lower(trim(p->>'nome'))
        AND created_at > now() - interval '10 minutes'
      ORDER BY created_at DESC
      LIMIT 1;

      IF v_num IS NOT NULL THEN
        -- 2a. Linha já finalizada ('processado' ou além)? Não pode voltar ao ciclo
        --     nem receber append -> orçamento NOVO com o payload completo
        IF EXISTS (
          SELECT 1 FROM %I.orcamentos
          WHERE numero_orcamento = v_num
            AND status_orcamento NOT IN ('aberto', 'processando')
        ) THEN
          v_num := NULL;

        -- 2b. Linha 'processando' que o payload NÃO contém identicamente (correção
        --     de valor ou dados gerais mudaram)? Não dá pra corrigir linha no ciclo
        --     -> orçamento NOVO completo. (Acréscimo puro passa: payload ⊇ linhas.)
        ELSIF EXISTS (
          SELECT 1 FROM %I.orcamentos t
          WHERE t.numero_orcamento = v_num
            AND t.status_orcamento = 'processando'
            AND NOT (
              t.estado = p->>'estado'
              AND t.data_inicio = p->>'data_inicio'
              AND t.data_fim = p->>'data_fim'
              AND t.concreto_usinado = coalesce(p->>'concreto_usinado', 'nao')
              AND t.paralisacao = coalesce(p->>'paralisacao', 'nao')
              AND t.meses_paralisados = coalesce(v_meses, '')
              AND EXISTS (
                SELECT 1 FROM jsonb_array_elements(p->'areas') a
                WHERE a->>'tipo' = t.tipo
                  AND a->>'categoria' = t.categoria
                  AND a->>'material' = t.material
                  AND (a->>'area_m2')::numeric = t.area_m2::numeric
                  AND a->>'is_principal' = t.is_principal
                  AND coalesce(a->>'coberta', '') = coalesce(t.coberta, '')
                  AND coalesce(a->>'prefabricado', 'nao') = coalesce(t.prefabricado, 'nao')
              )
            )
        ) THEN
          v_num := NULL;
        END IF;
      END IF;

      IF v_num IS NOT NULL THEN
        -- Mesma conversa, nada finalizado: linhas ainda 'aberto' são regravadas
        -- pelo payload (fonte da verdade); linhas 'processando' ficam INTACTAS
        DELETE FROM %I.orcamentos
        WHERE numero_orcamento = v_num
          AND status_orcamento = 'aberto';
      ELSE
        -- 3. Conversa/orçamento novo: número atômico AAMMDD + seq de 2 dígitos
        INSERT INTO %I.orcamento_seq AS os (dia, seq)
        VALUES (v_dia, 1)
        ON CONFLICT (dia) DO UPDATE SET seq = os.seq + 1
        RETURNING seq INTO v_seq;

        v_num := to_char(v_dia, 'YYMMDD') || lpad(v_seq::text, 2, '0');
      END IF;

      -- 4. Inserir uma linha por área — todas com o mesmo número.
      --    tipo/categoria/material/prefabricado são POR LINHA (reforma + demolição).
      --    Área que já existe como linha 'processando' deste número é PULADA
      --    (segue no ciclo; nunca duplica).
      FOR v_area IN SELECT * FROM jsonb_array_elements(p->'areas')
      LOOP
        IF EXISTS (
          SELECT 1 FROM %I.orcamentos t
          WHERE t.numero_orcamento = v_num
            AND t.status_orcamento = 'processando'
            AND t.tipo = v_area->>'tipo'
            AND t.categoria = v_area->>'categoria'
            AND t.material = v_area->>'material'
            AND t.area_m2::numeric = (v_area->>'area_m2')::numeric
            AND t.is_principal = v_area->>'is_principal'
            AND coalesce(t.coberta, '') = coalesce(v_area->>'coberta', '')
            AND coalesce(t.prefabricado, 'nao') = coalesce(v_area->>'prefabricado', 'nao')
        ) THEN
          CONTINUE;
        END IF;

        INSERT INTO %I.orcamentos
          (numero_orcamento, nome, telefone, session_id, estado, tipo, categoria, material,
           area_m2, is_principal, coberta, data_inicio, data_fim,
           concreto_usinado, paralisacao, prefabricado, meses_paralisados)
        VALUES
          (v_num,
           p->>'nome',
           p->>'telefone',
           p->>'session_id',
           p->>'estado',
           v_area->>'tipo',
           v_area->>'categoria',
           v_area->>'material',
           v_area->>'area_m2',
           v_area->>'is_principal',
           coalesce(v_area->>'coberta', ''),
           p->>'data_inicio',
           p->>'data_fim',
           coalesce(p->>'concreto_usinado', 'nao'),
           coalesce(p->>'paralisacao', 'nao'),
           coalesce(v_area->>'prefabricado', 'nao'),
           coalesce(v_meses, ''));
      END LOOP;

      RETURN v_num;
    END;
    $FUNC$ LANGUAGE plpgsql;
  $f$, v_schema, v_schema, v_schema, v_schema, v_schema, v_schema, v_schema, v_schema);

  -- ----------------------------------------------------------------------------
  -- 9. GRANT de permissões (obrigatório — diferente do schema "public", um
  --    schema novo NÃO recebe GRANT automático para as roles que a API REST
  --    do Supabase usa: anon, authenticated, service_role. Sem isso, toda
  --    chamada via API/supabase-py retorna "permission denied for schema"
  --    (42501), mesmo com o schema corretamente exposto/no search path.
  --
  --    Depois de rodar este arquivo, ainda é preciso ir em
  --    Settings > API > Exposed schemas e adicionar o schema manualmente
  --    (isso a API do Supabase não permite fazer via SQL).
  -- ----------------------------------------------------------------------------
  EXECUTE format('GRANT USAGE ON SCHEMA %I TO anon, authenticated, service_role', v_schema);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO anon, authenticated, service_role', v_schema);
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO anon, authenticated, service_role', v_schema);
  EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO anon, authenticated, service_role', v_schema);

  -- Garante que tabelas/sequences/funções criadas no futuro neste schema
  -- também recebam as mesmas permissões automaticamente
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO anon, authenticated, service_role', v_schema);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO anon, authenticated, service_role', v_schema);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role', v_schema);

  -- ----------------------------------------------------------------------------
  -- 10. Corrigir DEFAULT de created_at em tabelas JÁ EXISTENTES (idempotente).
  --     CREATE TABLE IF NOT EXISTS não altera estrutura de tabelas que já
  --     existem — isso garante que, ao rodar o script de novo num schema já
  --     criado (ex: para aplicar uma correção deste arquivo), o DEFAULT fique
  --     padronizado em now() puro, igual ao de um schema criado do zero.
  -- ----------------------------------------------------------------------------
  EXECUTE format('ALTER TABLE %I.orcamentos ALTER COLUMN created_at SET DEFAULT now()', v_schema);
  EXECUTE format('ALTER TABLE %I.inss ALTER COLUMN created_at SET DEFAULT now()', v_schema);
  EXECUTE format('ALTER TABLE %I.conversas_leads ALTER COLUMN created_at SET DEFAULT now()', v_schema);
  EXECUTE format('ALTER TABLE public.%I ALTER COLUMN created_at SET DEFAULT now()', v_schema || '_chat_histories');

  RAISE NOTICE 'Schema % criado/atualizado com sucesso (orcamentos, inss, conversas_leads, reengajamento_textos, orcamento_seq, função salvar_orcamento, permissões concedidas, defaults de created_at padronizados) + public.%_chat_histories (memória do AI Agent). Falta apenas expor o schema em Settings > API > Exposed schemas.', v_schema, v_schema;

END;
$MAIN$ LANGUAGE plpgsql;
